# Generated by Django 3.0.6 on 2020-06-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='people_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=4)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('profile_img', models.ImageField(upload_to='images/')),
                ('date_joined', models.DateTimeField()),
                ('last_login', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('reg_type', models.CharField(max_length=30)),
                ('email_key', models.CharField(max_length=10)),
                ('birth', models.DateField()),
            ],
        ),
    ]
