# Generated by Django 3.0.6 on 2020-06-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='people_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_data', models.CharField(max_length=400)),
                ('username', models.CharField(max_length=30)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
